Repository Macchina-CLI/macchina, pull requests merged in 2021-03, with the labels that each got.

#14 Full support for NetBSD!
  Cargo.lock
  Cargo.toml
  README.md
  README_CARGO.md
  src/display.rs
  src/format.rs
  src/read/battery.rs
  src/read/memory.rs
  src/read/package.rs
Labels: enhancement

#30 Use sysctl library instead of spawning process
  macchina-read/Cargo.toml
  macchina-read/src/linux/mod.rs
  macchina-read/src/macos/mod.rs
  macchina-read/src/shared/mod.rs
Labels: optimization

#34 Remove objc runtime, use sysctl instead to get os version
  Cargo.lock
  macchina-read/Cargo.toml
  macchina-read/src/lib.rs
  macchina-read/src/macos/mach_ffi.rs
  macchina-read/src/macos/mod.rs
Labels: optimization

#38 💻 Add more windows metrics
  Cargo.lock
  macchina-read/Cargo.toml
  macchina-read/build.rs
  macchina-read/src/shared/mod.rs
  macchina-read/src/windows/mod.rs
Labels: enhancement

#32 🎨 rework: theme implementation
  macchina/src/display.rs
  macchina/src/main.rs
  macchina/src/theme.rs
Labels: enhancement, optimization

#40 🎛 Use type-safe command line parsing with StructOpt and Clap
  Cargo.lock
  macchina/Cargo.toml
  macchina/src/display.rs
  macchina/src/main.rs
  macchina/src/theme.rs
Labels: enhancement

#51 ⚡ no longer query pacman to get number of installed packages
  macchina-read/src/linux/mod.rs
Labels: optimization

#53 ✨ feature: local ip address joins the club!
  Cargo.lock
  README.md
  README_CARGO.md
  macchina-read/Cargo.toml
  macchina-read/README.md
  macchina-read/src/linux/mod.rs
  macchina-read/src/macos/mod.rs
  macchina-read/src/traits.rs
  macchina-read/src/windows/mod.rs
  macchina/src/display.rs
  macchina/src/theme.rs
Labels: enhancement

#56 NetBSD battery fetching improvements
  Cargo.lock
  README.md
  README_CARGO.md
  macchina-read/Cargo.toml
  macchina-read/src/netbsd/mod.rs
Labels: optimization

#62 🔬 Add jemalloc as default allocator
  Cargo.lock
  macchina/Cargo.toml
  macchina/src/main.rs
Labels: optimization
